# Generated by Django 4.1.1 on 2022-09-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogroot', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
