# Generated by Django 4.1.1 on 2022-09-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogroot', '0003_remove_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='apolloblog', max_length=255),
        ),
    ]
