# Generated by Django 4.1.1 on 2022-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogroot', '0013_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
